/* This header generated by mk_method_wrappers from file /usr/include/lxc/lxccontainer.h
 * on Tue Feb 17 17:44:17 CET 2015.
 *
 * Do not edit!
 */

static int
lxc_CLONE_KEEPNAME(void) {
    return LXC_CLONE_KEEPNAME;
}

static int
lxc_CLONE_KEEPMACADDR(void) {
    return LXC_CLONE_KEEPMACADDR;
}

static int
lxc_CLONE_SNAPSHOT(void) {
    return LXC_CLONE_SNAPSHOT;
}

static int
lxc_CLONE_KEEPBDEVTYPE(void) {
    return LXC_CLONE_KEEPBDEVTYPE;
}

static int
lxc_CLONE_MAYBE_SNAPSHOT(void) {
    return LXC_CLONE_MAYBE_SNAPSHOT;
}

static int
lxc_CLONE_MAXFLAGS(void) {
    return LXC_CLONE_MAXFLAGS;
}

static int
lxc_CREATE_QUIET(void) {
    return LXC_CREATE_QUIET;
}

static int
lxc_CREATE_MAXFLAGS(void) {
    return LXC_CREATE_MAXFLAGS;
}

