/* This header generated by mk_method_wrappers from file /usr/include/lxc/lxccontainer.h
 * on Wed Feb 18 18:46:52 CET 2015.
 *
 * Do not edit!
 */

static int
lxc_CLONE_KEEPNAME(void) {
    return LXC_CLONE_KEEPNAME;
}

static int
lxc_CLONE_KEEPMACADDR(void) {
    return LXC_CLONE_KEEPMACADDR;
}

static int
lxc_CLONE_SNAPSHOT(void) {
    return LXC_CLONE_SNAPSHOT;
}

static int
lxc_CLONE_KEEPBDEVTYPE(void) {
    return LXC_CLONE_KEEPBDEVTYPE;
}

static int
lxc_CLONE_MAYBE_SNAPSHOT(void) {
    return LXC_CLONE_MAYBE_SNAPSHOT;
}

static int
lxc_CLONE_MAXFLAGS(void) {
    return LXC_CLONE_MAXFLAGS;
}

static int
lxc_CREATE_QUIET(void) {
    return LXC_CREATE_QUIET;
}

static int
lxc_CREATE_MAXFLAGS(void) {
    return LXC_CREATE_MAXFLAGS;
}

static int
lxc_ATTACH_LSM(void) {
    return LXC_ATTACH_LSM;
}

static int
lxc_ATTACH_KEEP_ENV(void) {
    return LXC_ATTACH_KEEP_ENV;
}

static int
lxc_ATTACH_CLEAR_ENV(void) {
    return LXC_ATTACH_CLEAR_ENV;
}

static int
lxc_ATTACH_MOVE_TO_CGROUP(void) {
    return LXC_ATTACH_MOVE_TO_CGROUP;
}

static int
lxc_ATTACH_DROP_CAPABILITIES(void) {
    return LXC_ATTACH_DROP_CAPABILITIES;
}

static int
lxc_ATTACH_SET_PERSONALITY(void) {
    return LXC_ATTACH_SET_PERSONALITY;
}

static int
lxc_ATTACH_LSM_EXEC(void) {
    return LXC_ATTACH_LSM_EXEC;
}

static int
lxc_ATTACH_REMOUNT_PROC_SYS(void) {
    return LXC_ATTACH_REMOUNT_PROC_SYS;
}

static int
lxc_ATTACH_LSM_NOW(void) {
    return LXC_ATTACH_LSM_NOW;
}

static int
lxc_ATTACH_DEFAULT(void) {
    return LXC_ATTACH_DEFAULT;
}

